stages:
  - build

debian11-job:
  stage: build
  when: manual
  image: librewolf/bsys4-buildenv-debian11
  script:
    - make -C source source_release
    - make -C source all
    - make -C build/debian11 ci
  artifacts:
    paths:
      - /artifacts/librewolf-*.tar.bz2
