
# (adjust for your folder with the sdk's and tools)
source_folder=../../bs4-cross-assets

all : MacOSX11.1-sdk.zip

MacOSX11.1-sdk.zip :
	cp -v ../../bs4-cross-assets/macos/MacOSX11.1-sdk.zip .

clean :
	rm -f MacOSX11.1-sdk.zip

veryclean : clean
